spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

luvoong:
  auth:
    jwt:
      secret: ENC(ArAUcqhLbVg0X/5P1kWQKhXublIj/7d28I5LdGfH5Cj+O4zvs54WijFOngEu96cT4xM5r+tMd5Va7/i5F8X+siAjA+rnRO2lcgyU1ohL1We0DXCSDoM7OYYOSSngWe62ONC92ksAv7vKyvmHZuAASVvneQcHQaEjrVyd3Ozf7xfVF02V3vaOpaTh/KyIJuonuuTC4l+mBzEXxT7iceLHewVghZmtRqoaOxMhb7y3zONkVX5d6vCXOg==)
      validity-in-seconds: 5
  web:
    cors:
      allowed-origins: http://localhost:5173

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    string-output-type: base64

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl

logging:
  level:
    com.luvoong.api: debug